server:
  port: 8071

# 自定义
custom:
  warehouse:
    path: /Users/izcw/MyFiles/Work/我的项目/note/NexNote/FileWarehouse/  # 指定静态资源的物理位置（与web.resources.static-locations一致）
  agreement-host: http://127.0.0.1 # 请求的协议+主机

spring:
  web:
    resources:
      static-locations: file:/Users/izcw/MyFiles/Work/我的项目/note/NexNote/FileWarehouse/ # 指定静态资源的物理位置（与custom.warehouse.path一致，需要多加file:前缀）

  datasource:
    url: "jdbc:mysql://localhost:3306/nexnote?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8"
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

  # redis
  data:
    redis:
      host: localhost # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-idle: 8 # 连接池最大空闲连接数
          min-idle: 0 # 连接池最小空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

